openapi: 3.0.0
info:
  title: 'calendar-three-trees-api'
  description: 'The REST api for the Calendar Three Trees App'
  version: 1.0.0

servers:
  - url: http://calendarapi.3treestech.ca/
    description: Main (development) server

components:
  schemas:
    Event:
      properties:
        name:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        moreInfoURL:
          type: string
          format: uri
        location:
          type: object
          properties:
            name:
              type: string
            address:
              type: string
            postalCode:
              type: string
              maximum: 6
              minimum: 6
        organizationId:
          type: integer
        tags:
          type: array
          items:
            type: string
      required:
        - name

paths:
  /groups/{groupId}/events/:
    parameters:
      - in: path
        name: groupId
        required: true
        schema:
          type: integer
          minimum: 1
        description: The id of the group
    post:
      summary: Creates a new event
      description: Create a new event in a specific group
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Returns the created event in a specific group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Bad or malformed request
        '401':
          description: Unauthorized request
    get:
      summary: Get events
      description: Get all the events in a specific group
      parameters:
        - in: query
          name: tags
          schema:
            type: array
            items:
              type: string
          description: The tags to be used to filter the events
        - in: query
          name: dates
          schema:
            type: array
            items:
              type: string
              format: date-time
          description: The dates to be used to filter the events
        - in: query
          name: dateRange
          schema:
            type: array
            items:
              type: string
              format: date-time
              minItems: 1
              maxItems: 2
          description: The date range to be used to filter the events
        - in: query
          name: contentSearchTerm
          schema:
            type: string
          description: the search terms to be used to filter the events
      responses:
        '200':
          description: Successfully retrieved searched events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          description: Bad or malformed request
        '401':
          description: Unauthorized request
        '404':
          description: No events found matching the search criteria
  /groups/{groupId}/events/{eventId}:
    parameters:
      - in: path
        name: groupId
        required: true
        schema:
          type: integer
          minimum: 1
        description: The id of the group
      - in: path
        name: eventId
        required: true
        schema:
          type: integer
          minimum: 1
        description: The id of the event
    delete:
      summary: Delete an event
      description: Delete an event in a specific group with a specific id
      responses:
        '204':
          description: Successfully deleted event
        '400':
          description: Bad or malformed request
        '401':
          description: Unauthorized request
        '404':
          description: Event not found
    put:
      summary: Update an event
      description: Update an event in a specific group with a specific id
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Event'
      responses:
        '204':
          description: Event successfully updated
        '400':
          description: Bad or malformed request
        '401':
          description: Unauthorized request
        '404':
          description: Event not found
    get:
      summary: Get an event
      description: Get an event in a specific group with a specific id
      responses:
        '200':
          description: Successfully retrieved an event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Bad or malformed request
        '401':
          description: Unauthorized request
        '404':
          description: Event not found
    