openapi: 3.0.0
info:
  title: 'calendar-three-trees-api'
  description: 'The REST api for the Calendar Three Trees App'
  version: 1.0.0

servers:
  - url: http://calendarapi.3treestech.ca/
    description: Main (development) server

components:
  schemas:
    Event:
      properties:
        id:
          type: integer
        name:
          type: string
        tags:
          type: array
          items:
            type: string
        content:
          type: string
        moreInfoURL:
          type: string
          format: uri
        contact:
          type: string
        eventDate:
          type: string
          format: date-time
        dateCreated:
          type: string
          format: date-time
        groupId:
          type: integer
      required:
        - id
        - name
        - dateCreated
        - groupId

paths:
  /groups/{groupId}/events/:
    parameters:
      - in: path
        name: groupId
        required: true
        schema:
          type: integer
          minimum: 1
        description: The id of the group
    post:
      summary: Creates a new event
      description: Create a new event in a specific group
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Returns the created event in a specific group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Bad or malformed request
        '401':
          description: Unauthorized request
  /groups/{groupId}/events/{eventId}:
    parameters:
      - in: path
        name: groupId
        required: true
        schema:
          type: integer
          minimum: 1
        description: The id of the group
      - in: path
        name: eventId
        required: true
        schema:
          type: integer
          minimum: 1
        description: The id of the event
    delete:
      summary: Delete an event
      description: Delete an event in a specific group with a specific id
      responses:
        '204':
          description: Successfully deleted event
        '400':
          description: Bad or malformed request
        '401':
          description: Unauthorized request
        '404':
          description: Event not found
    put:
      summary: Update an event
      description: Update an event in a specific group with a specific id
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Event'
      responses:
        '204':
          description: Event successfully updated
        '400':
          description: Bad or malformed request
        '401':
          description: Unauthorized request
        '404':
          description: Event not found
    get:
      summary: Get an event
      description: Get an event in a specific group with a specific id
      responses:
        '200':
          description: Successfully retrieved an event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Bad or malformed request
        '401':
          description: Unauthorized request
        '404':
          description: Event not found

